name: policies_migration

on:
  workflow_dispatch:
    inputs:
      policy_ids:
        description: "List of Policy ID's to be migrated"
        required: true
      target_vault_id:
        description: "Target Vault ID"
        required: true
      source_vault_access_token:
        description: "Access token of the Source Vault"
        required: true
      target_vault_access_token:
        description: "Access token of the Target Vault"
        required: true

jobs:
  execute-migration-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        env:
          POLICY_IDS: ${{ github.event.inputs.policy_ids }}
          TARGET_VAULT_ID: ${{ github.event.inputs.target_vault_id }}
          SOURCE_VAULT_AUTH: ${{ github.event.inputs.source_vault_access_token }}
          TARGET_VAULT_AUTH: ${{ github.event.inputs.target_vault_access_token }}
          SOURCE_VAULT_ACCOUNT_ID: ${{ vars.SOURCE_VAULT_ACCOUNT_ID }}
          TARGET_VAULT_ACCOUNT_ID: ${{ vars.TARGET_VAULT_ACCOUNT_ID }}
          SOURCE_VAULT_ENV_URL: ${{ vars.SOURCE_VAULT_ENV_URL }}
          TARGET_VAULT_ENV_URL: ${{ vars.TARGET_VAULT_ENV_URL }}
        run: python3 migrate_policies.py
