name: Vault Governance Migration script

on:
  workflow_dispatch:
    inputs:
      source_vault_id:
        description: "Vault ID of the Source Env"
        required: true
      target_vault_id:
        description: "Vault ID of the Target Env"
        required: true
      source_env_token:
        description: "Access token of the Source Env"
        required: true
      target_env_token:
        description: "Access token of the Target Env"
        required: true

jobs:
  execute-migration-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        env:
          SOURCE_VAULT_ID: ${{ github.event.inputs.source_vault_id }}
          TARGET_VAULT_ID: ${{ github.event.inputs.target_vault_id }}
          SOURCE_ENV_AUTH: ${{ github.event.inputs.source_env_token }}
          TARGET_ENV_AUTH: ${{ github.event.inputs.target_env_token }}
          SOURCE_ACCOUNT_ID: ${{ vars.SOURCE_ACCOUNT_ID }}
          TARGET_ACCOUNT_ID: ${{ vars.TARGET_ACCOUNT_ID }}
        run: python3 migrate_to_production.py
