name: vault_schema_and_governance_migration

on:
  workflow_dispatch:
    inputs:
      source_vault_id:
        description: "Source Vault ID"
        required: true
      workspace_id:
        description: "Workspace ID of the target account"
        required: true
      vault_name:
        description: "Name for the target vault. If not provided, source vault name will be used"
        required: false
      vault_description:
        description: "Description for the target vault. If not provided, source vault description will be used"
        required: false
      source_account_access_token:
        description: "Access token of the Source account"
        required: true
      target_account_access_token:
        description: "Access token of the Target account. Make sure to use a user generated access token from Studio."
        required: true

jobs:
  execute-schema-and-governance-migration-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run schema migration script
        id: schema_migration
        env:
          SOURCE_VAULT_ID: ${{ github.event.inputs.source_vault_id }}
          WORKSPACE_ID: ${{ github.event.inputs.workspace_id }}
          VAULT_NAME: ${{ github.event.inputs.vault_name }}
          VAULT_DESCRIPTION: ${{ github.event.inputs.vault_description }}
          SOURCE_ACCOUNT_AUTH: ${{ github.event.inputs.source_account_access_token }}
          TARGET_ACCOUNT_AUTH: ${{ github.event.inputs.target_account_access_token }}
          SOURCE_ACCOUNT_ID: ${{ vars.SOURCE_ACCOUNT_ID }}
          TARGET_ACCOUNT_ID: ${{ vars.TARGET_ACCOUNT_ID }}
          SOURCE_ENV_URL: ${{ vars.SOURCE_ENV_URL }}
          TARGET_ENV_URL: ${{ vars.TARGET_ENV_URL }}
          MIGRATE_GOVERNANCE: true
        run: python3 migrate_vault_schema.py
      
      - name: Run vault roles and policies migration script
        env:
          SOURCE_VAULT_ID: ${{ github.event.inputs.source_vault_id }}
          TARGET_VAULT_ID: ${{ env.TARGET_VAULT_ID }}
          SOURCE_ACCOUNT_AUTH: ${{ github.event.inputs.source_account_access_token }}
          TARGET_ACCOUNT_AUTH: ${{ github.event.inputs.target_account_access_token }}
          SOURCE_ACCOUNT_ID: ${{ vars.SOURCE_ACCOUNT_ID }}
          TARGET_ACCOUNT_ID: ${{ vars.TARGET_ACCOUNT_ID }}
          SOURCE_ENV_URL: ${{ vars.SOURCE_ENV_URL }}
          TARGET_ENV_URL: ${{ vars.TARGET_ENV_URL }}
        run: python3 migrate_vault_roles_and_policies.py
