name: update_service_account

on:
  workflow_dispatch:
    inputs:
      source_service_account_id:
        description: "Source Service account ID (Required to UPDATE_METADATA)"
        required: false
      target_service_account_id:
        description: "Target Service account ID"
        required: true
      update_service_account_criteria:
        description: 'Update Service account'
        required: true
        default: 'UPDATE_METADATA'
        type: choice
        options:
          - UPDATE_METADATA
          - ASSIGN_ROLES
      list_of_role_ids_to_assign:
        description: "List of Role IDs to assign"
        required: false
      source_account_access_token:
        description: "Access token of the Source Account (Required to UPDATE_METADATA)"
        required: false
      target_account_access_token:
        description: "Access token of the Target Account"
        required: true

jobs:
  execute-update-service-account-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script
        env:
          SOURCE_SERVICE_ACCOUNT_ID: ${{ github.event.inputs.source_service_account_id }}
          TARGET_SERVICE_ACCOUNT_ID: ${{ github.event.inputs.target_service_account_id }}
          UPDATE_SERVICE_ACCOUNT_CRITERIA: ${{ github.event.inputs.update_role_criteria }}
          ROLE_IDS: ${{ github.event.inputs.list_of_role_ids_to_assign }}
          SOURCE_ACCOUNT_AUTH: ${{ github.event.inputs.source_account_access_token }}
          TARGET_ACCOUNT_AUTH: ${{ github.event.inputs.target_account_access_token }}
          SOURCE_ACCOUNT_ID: ${{ vars.SOURCE_ACCOUNT_ID }}
          TARGET_ACCOUNT_ID: ${{ vars.TARGET_ACCOUNT_ID }}
          SOURCE_ENV_URL: ${{ vars.SOURCE_ENV_URL }}
          TARGET_ENV_URL: ${{ vars.TARGET_ENV_URL }}
        run: python3 update_service_account.py
